import {readFileSync,writeFileSync,renameSync,mkdirSync} from 'node:fs';
import {dirname} from 'node:path';
import {setTimeout as sleep} from 'node:timers/promises';
import {backfill,backfillWallet,candidateWallets,eligibleWalletsFromSupabase,relay,shouldRunHistorical,unfinishedWallets} from './worker.mjs';

function save(path,value){mkdirSync(dirname(path),{recursive:true});writeFileSync(path+'.tmp',JSON.stringify(value),{mode:0o600});renameSync(path+'.tmp',path)}
function supabaseState(url,key,checkpointKey,fetcher=fetch){const endpoint=new URL('/rest/v1/astratrader_meta',url),headers={apikey:key,authorization:'Bearer '+key,'content-type':'application/json'};return{async load(){for(const metaKey of [checkpointKey,'worker:checkpoint']){const u=new URL(endpoint);u.searchParams.set('key','eq.'+metaKey);u.searchParams.set('select','value');const r=await fetcher(u,{headers,signal:AbortSignal.timeout(15000),redirect:'error'});if(!r.ok)throw Error('Supabase checkpoint read HTTP '+r.status);const rows=await r.json();if(rows[0])return JSON.parse(rows[0].value)}return{}},async save(value){const u=new URL(endpoint);u.searchParams.set('on_conflict','key');const r=await fetcher(u,{method:'POST',headers:{...headers,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key:checkpointKey,value:JSON.stringify(value)}),signal:AbortSignal.timeout(15000),redirect:'error'});if(!r.ok)throw Error('Supabase checkpoint write HTTP '+r.status)}}}

async function main(){
 const e=process.env,url=e.ASTRATRADER_URL,token=e.INGEST_TOKEN,rpcURL=e.SOLANA_RPC_URL,backend=e.PERSISTENCE_BACKEND??(e.SUPABASE_URL?'supabase':'file'),path=e.BACKFILL_STATE_PATH??e.WORKER_STATE_PATH;
 const usingSupabase=backend==='supabase',loopMs=Math.max(1000,Math.min(60000,Number(e.BACKFILL_LOOP_MS??5000)||5000)),programBackfill=(e.HISTORY_BACKFILL_ENABLED??'false')==='true',programSize=Math.max(1,Math.min(20,Number(e.HISTORY_BACKFILL_SAMPLE_SIZE??3)||3)),walletSize=Math.max(1,Math.min(3,Number(e.WALLET_BACKFILL_SAMPLE_SIZE??3)||3));
 const missing=[['ASTRATRADER_URL',url],['INGEST_TOKEN',token?.length>=32],['SOLANA_RPC_URL',rpcURL],['PERSISTENCE_BACKEND',['file','supabase'].includes(backend)],['BACKFILL_STATE_PATH',usingSupabase||path],['SUPABASE_URL',!usingSupabase||e.SUPABASE_URL],['SUPABASE_SERVICE_ROLE_KEY',!usingSupabase||e.SUPABASE_SERVICE_ROLE_KEY?.length>=20],['PERSISTENCE_CONFIRMED',e.PERSISTENCE_CONFIRMED==='true']].filter(x=>!x[1]).map(x=>x[0]);
 if(missing.length)throw Error('Configure backfill worker environment: '+missing.join(', '));if(new URL(url).protocol!=='https:'||new URL(rpcURL).protocol!=='https:')throw Error('Use HTTPS endpoints');
 const remote=usingSupabase?supabaseState(e.SUPABASE_URL,e.SUPABASE_SERVICE_ROLE_KEY,'worker:checkpoint:backfill'):null;let state={};if(remote)state=await remote.load();else try{state=JSON.parse(readFileSync(path,'utf8'))}catch(error){if(error.code!=='ENOENT')throw Error('Backfill checkpoint unreadable')}
 const persist=remote?(s=>remote.save(s)):(s=>save(path,s));const programs=(e.DISCOVERY_PROGRAMS??'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4').split(',').map(x=>x.trim()).filter(Boolean);
 let stop=false,cycle=0;process.on('SIGTERM',()=>stop=true);process.on('SIGINT',()=>stop=true);
 const rpc=async(method,params)=>{const r=await fetch(rpcURL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:AbortSignal.timeout(15000),redirect:'error'});if(!r.ok)throw Error('RPC HTTP '+r.status);const j=await r.json();if(j.error)throw Error('RPC code '+j.error.code);if(!Array.isArray(j.result))throw Error('Unexpected RPC response');return j.result};
 while(!stop){const started=Date.now();let queued=0,stage='idle';try{if(programBackfill){stage='program-backfill';for(const program of programs)queued+=await backfill(program,state,rpc,(items,c)=>relay(items,url,token,fetch,c),()=>persist(state),programSize,'finalized')}
 stage='eligible-read';const eligible=usingSupabase?await eligibleWalletsFromSupabase(e.SUPABASE_URL,e.SUPABASE_SERVICE_ROLE_KEY):[];let pool=unfinishedWallets(eligible,state);if(!pool.length){stage='candidate-read';pool=unfinishedWallets(await candidateWallets(url,token),state)}if(pool.length){stage='wallet-backfill';const index=cycle%pool.length;queued+=await backfillWallet(pool[index],state,rpc,(items,c)=>relay(items,url,token,fetch,c),()=>persist(state),walletSize)}delete state['wallet-backfill:last-error'];await persist(state);cycle++;console.log(JSON.stringify({at:new Date().toISOString(),event:'backfill_checkpoint',eligible:eligible.length,pool:pool.length,queued,programBackfill,programSize,walletSize,cycle,cycleMs:Date.now()-started}))}catch(error){state['wallet-backfill:last-error']={at:Date.now(),stage,error:String(error?.message??error).slice(0,200)};try{await persist(state)}catch{}console.error(JSON.stringify({at:new Date().toISOString(),event:'backfill_failed',stage,error:String(error?.message??error).slice(0,160)}))}const remaining=loopMs-(Date.now()-started);if(remaining>0)await sleep(remaining)}
}
main().catch(e=>{console.error(e.message);process.exitCode=1});
